In [1]:
import pandas as pd
import numpy as np

In [21]:
Database = pd.read_csv("Database2025_data.csv", sep=";", skipfooter=3, engine='python')

In [22]:
Database

,PMID,Term,Terminology,Concept ID,True positive,False positive
0,973458,aldehydes,agrovoc,c_250,1.0,NaN
1,973458,aldehydes,mesh,D000447,1.0,NaN
2,973458,aliphatic aldehydes,chebi,CHEBI:59768,1.0,NaN
3,973458,amino,chebi,CHEBI:46882,1.0,NaN
4,973458,Amino,chebi,CHEBI:46882,1.0,NaN
...,...,...,...,...,...,...
5892,39114877,width,agrovoc,c_8387,NaN,1.0
5893,39114877,width,agrovoc,c_8387,NaN,1.0
5894,39114877,width,agrovoc,c_8387,NaN,1.0
5895,39114877,width,agrovoc,c_8387,NaN,1.0
5896,39114877,width,agrovoc,c_8387,NaN,1.0

In [25]:
Database['Terminology'].unique()

array(['agrovoc', 'mesh', 'chebi', 'atc', 'ncbitaxon_full', 'ott',
       'drugbank', 'lotus', 'pubchemmesh', 'psimi', 'ncit',
       'disprot_type3', 'disprot_type4', 'go_bp', 'uniprot_swissprot',
       'nextprot', 'covocbiomed', 'robiext', 'eco', 'go_cc',
       'affiliations', 'envo', 'covocdiseaseandsyndrom',
       'covocconceptualentities', 'go_mf', 'cellosaurus', 'po',
       'detectionmethods', 'covocorganism', 'mdd', 'ncbitaxon_models',
       'ppiptm', 'license', 'icdo3', 'covocgeographicloc', 'cellontology',
       'disprot_type1', 'disprot_type2', 'covocproteinsgenomes',
       'covocchemicals', 'flopo'], dtype=object)

In [38]:
# Filter Database for 'mesh' terminology only
mesh_data = Database[Database['Terminology'] == 'pubchemmesh']
print(f"Number of mesh entries: {len(mesh_data)}")
print(f"\nMesh terminology distribution:")
print(mesh_data['Terminology'].value_counts())
print(f"\nFirst few mesh entries:")
print(mesh_data.head())

Number of mesh entries: 371

Mesh terminology distribution:
Terminology
pubchemmesh    371
Name: count, dtype: int64

First few mesh entries:
      PMID                   Term  Terminology Concept ID  True positive  \
38  973458          ascorbic acid  pubchemmesh   54670067            1.0
39  973458          Ascorbic Acid  pubchemmesh   54670067            1.0
40  973458          Ascorbic Acid  pubchemmesh   54670067            1.0
62  973458  hydroxymethylfurfural  pubchemmesh     237332            1.0
71  973458             PQ6CK8PD0R  pubchemmesh   54670067            1.0

    False positive
38             NaN
39             NaN
40             NaN
62             NaN
71             NaN

In [5]:
Database['True positive'].unique()

array(['1', nan, '5274', '89,08'], dtype=object)

In [17]:
Cleaned_data = pd.read_csv("cleaned_target_entities.csv", sep = ';')
Cleaned_data

,PMID,Term,Terminology,Concept ID,True positive,False positive
0,973458,aliphatic aldehydes,chebi,CHEBI:59768,1.0,NaN
1,973458,amino,chebi,CHEBI:46882,1.0,NaN
2,973458,Amino,chebi,CHEBI:46882,1.0,NaN
3,973458,Amino,chebi,CHEBI:46882,1.0,NaN
4,973458,amino acids,atc,B05BA01,1.0,NaN
...,...,...,...,...,...,...
716,39114877,albumin,atc,B05AA01,1.0,NaN
717,39114877,albumin,atc,B05AA01,1.0,NaN
718,39114877,albumin,atc,B05AA01,1.0,NaN
719,39114877,albumin,atc,B05AA01,1.0,NaN
720,39114877,Albumin,atc,B05AA01,1.0,NaN